### ISSUE TITLE
Design API 

### ISSUE THREAD

**Issue by shopetan** [jphacks/TK_07#11]
催促すると増えるらしい

**Comment by shopetan** [comment]
# Usage API 

|    Route    |   HTTP Verb  |  Description |
|:-----------:|:------------:|:------------:|
| /search                |      GET     |     Post a test message.                |

まずは空jsonを返しましょうね~~~

**Comment by shopetan** [comment]
要望に合わせて徐々に増える

**Comment by makky3939** [comment]
GET /results
GET /results/:result_id

POST /favorites/:result_id
GET /favorites/:result_id

**Comment by makky3939** [comment]
/searchに関しては api/v1/search Controllerを作って indexアクションを叩く感じにした方がいいと思います
